BBCLASSEXTEND = "native"
PACKAGE_ARCH := "${MACHINE_ARCH}"

FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}-${PV}:"

EXTRA_DIRECTFB ?= "empty"
EXTRA_DIRECTFB:vu7376 = "vuplus"
EXTRA_DIRECTFB:vu7376duo = "vuplus"
EXTRA_DIRECTFB:vuuno4k = "vuplus"
EXTRA_DIRECTFB:vuuno4kse = "vuplus"
EXTRA_DIRECTFB:vuzero4k = "vuplus"
EXTRA_DIRECTFB:cc1 = "hisi"
EXTRA_DIRECTFB:ocmv200 = "hisi"
EXTRA_DIRECTFB:sx988 = "hisi"
EXTRA_DIRECTFB:sfx6008 = "hisi"
EXTRA_DIRECTFB:ustym4kpro = "hisi"
EXTRA_DIRECTFB:ustym4kottpremium = "hisi"
EXTRA_DIRECTFB:ustym4ks2ottx = "hisi"
EXTRA_DIRECTFB:gbmv200 = "hisi"
EXTRA_DIRECTFB:beyonwizv2 = "hisi"
EXTRA_DIRECTFB:viper4k = "hisi"
EXTRA_DIRECTFB:dual = "hisi"
EXTRA_DIRECTFB:og2ott4k = "hisi"
EXTRA_DIRECTFB:og2s4k = "hisi"
EXTRA_DIRECTFB:ip8 = "hisi"
EXTRA_DIRECTFB:sx88v2 = "hisi"

require directfb-${EXTRA_DIRECTFB}_1.7.7.inc

INSANE_SKIP += "32bit-time"
TARGET_CFLAGS += "-Wa,--noexecstack"
